# Generated by Django 5.2 on 2026-05-19 07:23

import datetime
import django.db.models.deletion
import nepali_datetime_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EduSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTermStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('canonical_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city_id', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('website', models.URLField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('logo', models.FileField(blank=True, upload_to='school/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shortcode', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('is_branch', models.BooleanField(default=False)),
                ('min_reg', models.BigIntegerField(blank=True, null=True)),
                ('max_reg', models.BigIntegerField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=250, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
            ],
        ),
        migrations.CreateModel(
            name='LiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('grade_list', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('calculation_type', models.CharField(default='legacy', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('grade_weight', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.gradelevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
            ],
            options={
                'unique_together': {('school', 'grade_name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolResultType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200)),
                ('name_in_short', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('final_term', models.BooleanField(default=False)),
                ('final_term_name', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sms.schooltermstatus')),
            ],
            options={
                'unique_together': {('year', 'school', 'term_name')},
            },
        ),
        migrations.CreateModel(
            name='ResultManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_calculation', models.CharField(max_length=500)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('school_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
            ],
            options={
                'unique_together': {('grade', 'section', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.TextField()),
                ('nepali_date', nepali_datetime_field.models.NepaliDateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('pin_code', models.IntegerField()),
                ('name', models.CharField(max_length=125)),
                ('gender', models.BooleanField()),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('iemis', models.BigIntegerField(blank=True, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=150, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('fathers_phone', models.BigIntegerField(blank=True, null=True)),
                ('fathers_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mothers_phone', models.BigIntegerField(blank=True, null=True)),
                ('mothers_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_phone', models.BigIntegerField(blank=True, null=True)),
                ('guardian_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('publish_result', models.BooleanField(default=True)),
                ('added', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.house')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('total_mark', models.IntegerField()),
                ('section_rank', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_school_days', models.IntegerField()),
                ('no_of_present_days', models.IntegerField()),
                ('no_of_absent_days', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('heavy_weight', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('subject_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.subjectmaster')),
            ],
            options={
                'unique_together': {('session', 'branch', 'grade', 'section', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeFullMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_fm', models.IntegerField()),
                ('pr_fm', models.IntegerField()),
                ('th_pm', models.IntegerField()),
                ('pr_pm', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SuperBranchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.BigIntegerField()),
                ('range_end', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.superbranchuser'),
        ),
        migrations.CreateModel(
            name='BranchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_status', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.superbranchuser')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('previous_data', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('mo', models.CharField(max_length=500)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
            ],
        ),
        migrations.CreateModel(
            name='CreatedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('previous_data', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('added_by', 'guardian')},
            },
        ),
        migrations.CreateModel(
            name='StudentComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_points', models.JSONField(blank=True, default=list)),
                ('negative_points', models.JSONField(blank=True, default=list)),
                ('teacher_suggestions', models.JSONField(blank=True, default=list)),
                ('final_verdict', models.CharField(choices=[('good_progress', 'Good Progress'), ('need_attention', 'Need Attention'), ('immediate_concern', 'Immediate Concern')], max_length=20)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
            ],
            options={
                'unique_together': {('student', 'session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
            ],
            options={
                'unique_together': {('session', 'student', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='MarkObtained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_mo', models.IntegerField()),
                ('pr_mo', models.IntegerField()),
                ('is_absent', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolgrade')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
            ],
            options={
                'unique_together': {('student', 'session', 'school', 'grade', 'term', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'student')},
            },
        ),
        migrations.CreateModel(
            name='WeightedResultManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('school_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolterm')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
            ],
            options={
                'unique_together': {('school', 'year', 'school_term')},
            },
        ),
    ]
