# Generated by Django 6.0.1 on 2026-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='students/avatars/'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='students/sessions/'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='parent_can_view_homework',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='parent_can_view_result',
            field=models.BooleanField(default=True),
        ),
    ]
