# Generated by Django 5.2 on 2026-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_student_avatar_studentsession_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbranch',
            name='shortcode',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
