# Generated by Django 6.0.1 on 2026-05-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_schoolbranch_shortcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch'),
        ),
        migrations.AddField(
            model_name='subjectmaster',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'grade', 'section', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectmaster',
            unique_together={('school', 'canonical_name'), ('school', 'code')},
        ),
    ]
