# Generated by Django 6.0.1 on 2026-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_section_unique_together_section_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaster',
            name='canonical_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectmaster',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
