# Generated by Django 6.0.1 on 2026-05-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_subjectmaster_canonical_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('session', 'branch', 'grade', 'section', 'subject'), ('session', 'grade', 'subject_master')},
        ),
    ]
