# Generated by Django 5.2 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_add_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
