# Generated by Django 6.0.1 on 2026-06-23 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_platformsetting_teacher_external_id_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('platform_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.edusession')),
            ],
        ),
    ]
