# Generated by Django 6.0.1 on 2026-06-29 20:14

import sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_parentmessagelog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=sms.models.student_avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=sms.models.student_session_avatar_upload_path),
        ),
    ]
