# Generated by Django 6.0.1 on 2026-07-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_student_avatar_alter_studentsession_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.schoolbranch'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'session', 'school')},
        ),
    ]
