# Generated by Django 6.0.1 on 2026-07-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_group_unique_together_group_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_or_email', models.CharField(max_length=100, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembershipCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_user_id', models.CharField(max_length=100)),
                ('role', models.CharField(default='member', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_members', to='sms.group')),
            ],
            options={
                'unique_together': {('group', 'platform_user_id')},
            },
        ),
    ]
