# Generated by Django 6.0.1 on 2026-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_platformusermapping_groupmembershipcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranch',
            name='business_key',
            field=models.CharField(blank=True, help_text='Delegated Hamro API business key for this school', max_length=255, null=True),
        ),
    ]
