# Generated by Django 6.0.1 on 2026-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_add_business_key_to_school_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbranch',
            name='class_groups_as_channel',
            field=models.BooleanField(default=False, help_text='Class/section groups as channel (broadcast) instead of group (discussion)'),
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='school_channel_as_channel',
            field=models.BooleanField(default=True, help_text='School-wide announcements as channel (broadcast)'),
        ),
        migrations.AddField(
            model_name='schoolbranch',
            name='teachers_as_channel',
            field=models.BooleanField(default=False, help_text='Teachers group as channel (broadcast) instead of group (discussion)'),
        ),
    ]
