# Generated by Django 6.0.1 on 2026-07-17 10:59

from django.db import migrations, models


def backfill_group_type(apps, schema_editor):
    Group = apps.get_model('sms', 'Group')
    # School-wide broadcast channels
    Group.objects.filter(
        is_broadcast=True, grade__isnull=True, section__isnull=True
    ).update(group_type='school')
    # School-wide non-broadcast groups (teachers)
    Group.objects.filter(
        is_broadcast=False, grade__isnull=True, section__isnull=True
    ).update(group_type='teachers')


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_add_thread_type_config_to_school_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('school', 'School Channel/Group'), ('teachers', 'Teachers Channel/Group'), ('class', 'Class/Section Group')], default='class', max_length=20),
        ),
        migrations.RunPython(backfill_group_type, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('group_type', 'session', 'school', 'grade', 'section')},
        ),
    ]
