# Generated by Django 6.0.1 on 2026-07-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_add_group_type_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_short', models.CharField(default='TH', max_length=10)),
                ('theory_long', models.CharField(default='Theory', max_length=50)),
                ('practical_short', models.CharField(default='PR', max_length=10)),
                ('practical_long', models.CharField(default='Practical', max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminology', to='sms.schoolbranch')),
            ],
            options={
                'verbose_name': 'School Terminology',
                'verbose_name_plural': 'School Terminologies',
            },
        ),
    ]
