# Generated by Django 5.2 on 2026-05-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamrouserprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
